//! Gathering everything this machine will tell us, for one text file.
//!
//! The shape of the report and everything that can be rendered from a disk
//! image live in [`gptcore::diag`]. This module is the half that needs
//! firmware: the variable store, the protocols, the volumes.
//!
//! It answers a question the screens deliberately do not. Every other view
//! in this tool is built for somebody standing in front of the machine, and
//! is therefore ruthless about what it leaves out — a screen that says
//! everything says nothing on a 7-inch panel. But the person who ends up
//! solving a strange boot failure is usually not that operator; it is
//! whoever reads their forum post, who cannot press View, cannot ask a
//! cheap follow-up question, and has no way to know which of the forty
//! things the machine could have said were the ones that got dropped. So
//! this collects all of them, once, into a file that can be attached.
//!
//! Nothing here writes anything. Reading the report never changes the
//! machine it describes, which is also what makes it safe to offer as the
//! first thing to do on a machine somebody is frightened of.

use crate::selfdev::BootDevice;
use crate::{espscan, fwcrc, nvram, secureboot, smbios, store, ui};
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use gptcore::bootopt;
use gptcore::diag::{field, field_as, field_key, section};
use gptcore::report::human_size;
use gptcore::style::{bad, dim, good, key, line, title, warn, Line, Style};
use uefi::boot::{self, SearchType};
use uefi::proto::device_path::DevicePath;
use uefi::proto::media::block::BlockIO;
use uefi::runtime::{self, VariableAttributes, VariableVendor};
use uefi::Identify;

/// Build the whole report.
///
/// The disks are scanned first and their analyses carried through, for the
/// same reason [`crate::Disk`] carries one: reading a GPT is four block
/// reads and two CRCs, and the alternative is doing it again for every
/// section that mentions a disk. It also settles the ordering question
/// [`fwcrc::used_fallback`] raises — whether the firmware's CRC32 was
/// usable is only known after something has asked it for one.
pub fn build(boot_device: &BootDevice) -> Vec<Line> {
    let disks = crate::scan(boot_device);
    let state = nvram::read();
    let esps = espscan::scan(boot_device, &crate::known_paths(&state));

    let mut out = preamble();
    out.extend(system());
    out.extend(firmware(boot_device));
    out.extend(secure_boot());
    out.extend(block_devices(boot_device));
    out.extend(tables(&disks));
    out.extend(boot_entries(&state));
    out.extend(bootloaders(&esps));
    out.extend(volumes());
    out.extend(variable_store());
    out.push(Line::blank());
    out.push(title(&"-".repeat(gptcore::diag::WIDTH)[..]));
    out.push(dim("End of report."));
    out
}

fn preamble() -> Vec<Line> {
    let rule = "=".repeat(gptcore::diag::WIDTH);
    alloc::vec![
        title(rule.clone()),
        title(crate::app_name()),
        title("Diagnostic report"),
        title(rule),
        Line::blank(),
        field_key("generated by", format!("bootfixr {}", env!("BOOTFIXR_VERSION"))),
        field_key("generated at", format!("{} (the firmware's own clock)", crate::now())),
        Line::blank(),
        line("  This file was produced by gathering information on this machine."),
        line("  It is meant to be attached to a forum post or a bug report:"),
        line("  it holds the partition tables, the firmware's boot config"),
        line("  and the bootloaders installed on this machine,"),
        line("  which between them answer most of the questions anyone helping"),
        line("  would otherwise have to ask one at a time."),
        Line::blank(),
        // The file gets the same warning the screen does, because the two
        // are read by different people: the screen by whoever saved it, this
        // by whoever is about to paste it somewhere.
        warn("  BEFORE PUBLISHING IT: there are no passwords here and nothing"),
        warn("  off your filesystems, and the serial numbers and system UUID"),
        warn("  below are masked. It does still identify this machine, by its"),
        warn("  model, its partition GUIDs, and device paths that can carry a"),
        warn("  USB device's serial. A boot entry can also hold a command line."),
        warn("  Feel free to trim any data that you're not comfortable publishing."),
    ]
}

/// What the machine says it is: model, board, BIOS, processor.
///
/// First after the preamble, and deliberately: it is the question anybody
/// reading the report asks before any other, and on a handheld the answer
/// decides whether the rest of the file is even about the same hardware as
/// the thread it was posted in.
fn system() -> Vec<Line> {
    let mut out = section("This machine (SMBIOS)");
    match smbios::table() {
        Some(bytes) => out.extend(gptcore::smbios::render(&bytes)),
        None => {
            out.push(dim("  This firmware publishes no SMBIOS table, so it will not say"));
            out.push(dim("  what machine this is. The firmware vendor below is all there"));
            out.push(dim("  is to go on."));
        }
    }
    out
}

// ------------------------------------------------------------- the firmware

fn firmware(boot_device: &BootDevice) -> Vec<Line> {
    let mut out = section("Firmware and this program");
    let vendor = uefi::system::firmware_vendor().to_string();
    out.push(field_key(
        "firmware",
        if vendor.is_empty() {
            String::from("<the firmware gave no vendor string>")
        } else {
            vendor
        },
    ));
    out.push(field("firmware revision", format!("{:#x}", uefi::system::firmware_revision())));
    let rev = uefi::system::uefi_revision();
    out.push(field("UEFI revision", format!("{}.{}", rev.major(), rev.minor())));
    out.push(field("this program", format!("bootfixr {}", env!("BOOTFIXR_VERSION"))));

    if boot_device.is_known() {
        out.push(field_key("launched from", crate::path_text(boot_device.path())));
    } else {
        out.push(field_as(
            Style::Warn,
            "launched from",
            "unknown - the firmware would not say where this image came from",
        ));
    }

    // Which CRC32 was used is not trivia: a mismatch between the
    // firmware's and ours would show up as a table this tool calls corrupt
    // and every other tool calls fine.
    out.push(field(
        "CRC32",
        if fwcrc::used_fallback() {
            "the built-in implementation (the firmware's was unavailable)"
        } else {
            "the firmware's CalculateCrc32"
        },
    ));

    let (cols, rows) = ui::size();
    let screen = match crate::ui::term::rotation() {
        Some(r) => format!("{cols}x{rows} characters, drawn on the framebuffer, {}", r.name()),
        None => format!("{cols}x{rows} characters, the firmware's own text console"),
    };
    out.push(field("screen", screen));

    out.push(Line::blank());
    out.push(title("  NVRAM space, as the firmware reports it:"));
    out.extend(nvram_space());
    out.push(Line::blank());
    out.push(title("  Configuration tables the firmware publishes:"));
    out.extend(config_tables());
    out
}

/// The well-known tables the firmware hands over, named where we know them.
///
/// One line, and it settles several questions at once: whether there is an
/// SMBIOS table to read a machine's model out of, whether ACPI 2.0 is
/// present, and whether the firmware publishes an ESRT — which is how a
/// machine says it takes capsule updates at all.
fn config_tables() -> Vec<Line> {
    use uefi::table::cfg;
    const KNOWN: &[(uefi::Guid, &str)] = &[
        (cfg::ACPI_GUID, "ACPI 1.0"),
        (cfg::ACPI2_GUID, "ACPI 2.0"),
        (cfg::SMBIOS_GUID, "SMBIOS"),
        (cfg::SMBIOS3_GUID, "SMBIOS 3"),
        (cfg::ESRT_GUID, "ESRT"),
        (cfg::DEBUG_IMAGE_INFO_GUID, "debug image info"),
        (cfg::MEMORY_TYPE_INFORMATION_GUID, "memory type information"),
        (cfg::DXE_SERVICES_GUID, "DXE services"),
    ];

    uefi::system::with_config_table(|tables| {
        let mut named = Vec::new();
        let mut others = 0usize;
        for entry in tables {
            match KNOWN.iter().find(|(guid, _)| *guid == entry.guid) {
                Some((_, name)) => named.push(*name),
                None => others += 1,
            }
        }
        let mut out = alloc::vec![field(
            "recognised",
            if named.is_empty() { String::from("none") } else { named.join(", ") }
        )];
        out.push(field("unrecognised", format!("{others}")));
        out
    })
}

/// How much room is left for boot entries.
///
/// `OUT_OF_RESOURCES` from `SetVariable` is a refusal this tool already
/// explains, but only after the operator has tried. Reported here it is a
/// prediction instead, and a store that is nearly full is a plausible cause
/// of a boot entry that vanished on its own.
fn nvram_space() -> Vec<Line> {
    let attrs = VariableAttributes::NON_VOLATILE
        .union(VariableAttributes::BOOTSERVICE_ACCESS)
        .union(VariableAttributes::RUNTIME_ACCESS);
    match runtime::query_variable_info(attrs) {
        Ok(info) => alloc::vec![
            field("total", human_size(info.maximum_variable_storage_size)),
            field("free", human_size(info.remaining_variable_storage_size)),
            field("largest variable", human_size(info.maximum_variable_size)),
        ],
        Err(e) => alloc::vec![dim(format!("    the firmware would not say ({:?})", e.status()))],
    }
}

fn secure_boot() -> Vec<Line> {
    let sb = secureboot::read();
    let mut out = section("Secure Boot");
    out.push(field_key("state", sb.summary()));
    out.push(Line::blank());
    for (name, value, meaning) in [
        ("SecureBoot", sb.secure_boot, "1 = signatures are being enforced"),
        ("SetupMode", sb.setup_mode, "1 = no platform key; keys may be enrolled"),
        ("AuditMode", sb.audit_mode, "1 = verifying but not refusing"),
        ("DeployedMode", sb.deployed_mode, "1 = fully deployed, cannot return to setup"),
        ("VendorKeys", sb.vendor_keys, "0 = the keys were changed after manufacture"),
    ] {
        match value {
            Some(v) => out.push(field(name, format!("{v}    ({meaning})"))),
            None => out.push(field_as(Style::Dim, name, "not present")),
        }
    }

    out.push(Line::blank());
    out.push(title("  Key databases (sizes only; the keys themselves are not read):"));
    for db in &sb.databases {
        let value = match &db.size {
            Ok(Some(n)) => format!("{n} bytes"),
            Ok(None) => String::from("not present"),
            Err(e) => e.clone(),
        };
        out.push(field(db.name, value));
    }
    out.push(Line::blank());
    out.push(dim("  This program never enrols, clears or modifies any of these."));
    out
}

// ------------------------------------------------------------ block devices

/// Every block device the firmware knows about, including the ones the
/// repair paths refuse.
///
/// The refusals are the point. "There are no disks to repair" is a
/// confusing screen when the machine plainly has a drive in it, and the
/// answer is always in this list: the drive is removable, or read-only, or
/// the firmware only published partitions for it.
fn block_devices(boot_device: &BootDevice) -> Vec<Line> {
    let mut out = section("Block devices the firmware publishes");
    let Ok(handles) = boot::locate_handle_buffer(SearchType::ByProtocol(&BlockIO::GUID)) else {
        out.push(bad("  The firmware published no block devices at all."));
        return out;
    };

    out.push(dim(format!("  {} handles carry EFI_BLOCK_IO_PROTOCOL.", handles.len())));
    out.push(dim("  [target] marks a device the repair paths are willing to write to."));
    out.push(Line::blank());

    for (i, handle) in handles.iter().copied().enumerate() {
        let Ok(io) = crate::get_protocol::<BlockIO>(handle) else {
            out.push(bad(format!("  {:>2}  the protocol could not be opened", i + 1)));
            continue;
        };
        let media = io.media();
        let (block_size, last_block) = (media.block_size(), media.last_block());
        let mut flags =
            alloc::vec![
                if media.is_logical_partition() { "partition" } else { "whole disk" }.to_string()
            ];
        flags.push(if media.is_removable_media() { "removable" } else { "fixed" }.to_string());
        if !media.is_media_present() {
            flags.push(String::from("no media"));
        }
        if media.is_read_only() {
            flags.push(String::from("read-only"));
        }
        let target = !media.is_logical_partition()
            && !media.is_removable_media()
            && media.is_media_present()
            && !media.is_read_only();
        drop(io);

        let path = crate::get_protocol::<DevicePath>(handle).ok();
        if crate::over_usb(path.as_deref()) {
            flags.push(String::from("over USB"));
        }
        if path.as_deref().is_some_and(|p| boot_device.covers(p)) {
            flags.push(String::from("carries the volume this program came from"));
        }
        if target {
            flags.push(String::from("[target]"));
        }

        out.push(key(format!("  {:>2}  {}", i + 1, flags.join(", "))));
        out.push(line(format!(
            "      {} blocks x {} B = {}",
            last_block + 1,
            block_size,
            human_size((last_block + 1).saturating_mul(block_size as u64))
        )));
        out.push(dim(format!("      {}", crate::path_text(path.as_deref()))));
    }
    out
}

// -------------------------------------------------------------- the tables

fn tables(disks: &[crate::Disk]) -> Vec<Line> {
    let mut out = section("Partition tables");
    if disks.is_empty() {
        out.push(bad("  No fixed, writable, whole disk was found."));
        out.push(dim("  The block device list above says why."));
        return out;
    }

    for disk in disks {
        out.push(Line::blank());
        out.push(title(format!("  {}", disk.label())));
        out.push(dim(format!("  {}", disk.path)));
        match &disk.analysis {
            Ok(analysis) => out.extend(gptcore::diag::render_disk(analysis)),
            Err(e) => out.push(bad(format!("    the table could not be read - {e}"))),
        }
    }
    out
}

// -------------------------------------------------------------- the entries

fn boot_entries(state: &nvram::BootState) -> Vec<Line> {
    let mut out = section("Boot entries in NVRAM");
    if let Some(e) = &state.truncated {
        out.push(bad(format!("  {e}")));
        out.push(warn("  The list below may be incomplete."));
    }

    out.push(field_key(
        "booted from",
        match state.current {
            Some(s) => crate::slot_with_name(state, s),
            None => String::from("the firmware did not say"),
        },
    ));
    match state.next {
        Some(n) => out.push(field_key("next boot only", crate::slot_with_name(state, n))),
        None => out.push(field("next boot only", "not set")),
    }
    match state.timeout {
        Some(t) => out.push(field("menu timeout", format!("{t} s"))),
        None => out.push(field("menu timeout", "not set")),
    }

    match &state.order {
        Err(e) => out.push(field_as(Style::Bad, "boot order", format!("cannot be read - {e}"))),
        Ok(order) if order.is_empty() => {
            out.push(field_as(Style::Bad, "boot order", "EMPTY - the firmware has no list to try"))
        }
        Ok(order) => {
            let names: Vec<String> = order.iter().map(|s| bootopt::slot_name(*s)).collect();
            out.push(field_key("boot order", names.join(", ")));
        }
    }

    let orphans = state.orphans();
    if !orphans.is_empty() {
        let names: Vec<String> = orphans.iter().map(|s| bootopt::slot_name(*s)).collect();
        out.push(field_as(
            Style::Warn,
            "not in the order",
            format!("{}  (present, but the firmware will not offer them)", names.join(", ")),
        ));
    }

    out.push(Line::blank());
    if state.entries.is_empty() {
        out.push(bad("  There are no Boot#### entries in NVRAM at all."));
        return out;
    }
    out.push(title(format!(
        "  All {} entries in the store, lowest slot first:",
        state.entries.len()
    )));
    for (slot, entry) in &state.entries {
        out.push(Line::blank());
        out.extend(one_entry(state, *slot, entry));
    }
    out
}

/// One `Boot####`, in as much detail as it has.
fn one_entry(
    state: &nvram::BootState,
    slot: u16,
    entry: &Result<bootopt::LoadOption, String>,
) -> Vec<Line> {
    let opt = match entry {
        Ok(opt) => opt,
        Err(e) => {
            return alloc::vec![bad(format!(
                "  {}  WILL NOT DECODE - {e}",
                bootopt::slot_name(slot)
            ))]
        }
    };
    let position = match &state.order {
        Ok(order) => match order.iter().position(|s| *s == slot) {
            Some(i) => format!("{} of {} in the boot order", i + 1, order.len()),
            None => String::from("NOT in the boot order"),
        },
        Err(_) => String::from("the boot order could not be read"),
    };

    let mut out = alloc::vec![
        key(format!("  {}  \"{}\"", bootopt::slot_name(slot), opt.description)),
        line(format!("      {position}")),
        line(format!("      attributes {:#010x}", opt.attributes)),
    ];
    for l in bootopt::render_flags(opt) {
        out.push(Line::new(format!("      {}", l.text.trim_start()), l.style));
    }
    let path = crate::boot_path_text(&opt.device_path);
    if path.is_empty() {
        out.push(warn("      no device path at all"));
    } else {
        // Deliberately not wrapped: see the note in gptcore::diag. This is
        // the line somebody will want to compare against another machine's.
        out.push(line(format!("      {path}")));
    }
    if !opt.optional_data.is_empty() {
        out.push(dim("      load options, in hex:"));
        for l in hex_dump(&opt.optional_data, "        ") {
            out.push(dim(l));
        }
    }
    out
}

/// How much of a load option's trailing data is worth printing.
///
/// Enough for a kernel command line, which is what is usually in there and
/// is the only part anyone reads. A loader that stores something larger is
/// storing something this report cannot interpret anyway, so the rest is
/// counted rather than dumped.
const HEX_LIMIT: usize = 256;

fn hex_dump(bytes: &[u8], indent: &str) -> Vec<String> {
    let shown = bytes.len().min(HEX_LIMIT);
    let mut out = Vec::new();
    for chunk in bytes[..shown].chunks(16) {
        let mut hex = String::new();
        let mut text = String::new();
        for b in chunk {
            hex.push_str(&format!("{b:02x} "));
            text.push(if (0x20..0x7f).contains(b) { *b as char } else { '.' });
        }
        out.push(format!("{indent}{hex:<48} {text}"));
    }
    if bytes.len() > shown {
        out.push(format!("{indent}... and {} more bytes", bytes.len() - shown));
    }
    out
}

// ---------------------------------------------------------- the ESP content

fn bootloaders(scan: &espscan::Scan) -> Vec<Line> {
    let mut out = section("Bootloaders on the EFI System Partitions");
    if scan.volumes.is_empty() {
        out.push(bad("  No EFI System Partition was found on a fixed disk."));
        out.push(dim("  Removable media is not scanned: a boot entry pointing at a stick"));
        out.push(dim("  stops working the moment it is unplugged."));
        return out;
    }

    for (i, volume) in scan.volumes.iter().enumerate() {
        out.push(Line::blank());
        let mut heading = format!("  ESP {}", i + 1);
        if volume.boot {
            heading.push_str("  (this program was launched from it)");
        }
        out.push(title(heading));
        out.push(dim(format!("    {}", volume.path)));
        out.push(field("partition GUID", volume.partition.to_string()));

        if scan.unreadable.contains(&i) {
            out.push(bad("    The filesystem on this ESP could not be opened."));
            continue;
        }
        let found: Vec<&espscan::Candidate> =
            scan.candidates.iter().filter(|c| c.esp == i).collect();
        if found.is_empty() {
            out.push(warn("    No EFI binaries on this ESP."));
            continue;
        }
        for c in found {
            out.push(key(format!("    {}", c.file)));
            out.push(line(format!("        {}, {}", c.kind, human_size(c.size))));
            match c.registered {
                Some(slot) => {
                    out.push(good(format!("        registered as {}", bootopt::slot_name(slot))))
                }
                None => out.push(warn("        no NVRAM boot entry points at it")),
            }
        }
    }
    if scan.truncated {
        out.push(Line::blank());
        out.push(warn("  Some directories were nested too deep to scan; the list above"));
        out.push(warn("  may be incomplete."));
    }
    out
}

// ------------------------------------------------------------- our own files

/// The volumes this tool can keep files on, and what it has kept on them.
///
/// Worth a section of its own because it answers "is there anything to
/// restore from?" without the operator having to walk into the restore
/// screen to find out — and because a report that names the snapshots
/// alongside them is what makes a snapshot findable a year later.
fn volumes() -> Vec<Line> {
    let mut out = section("Volumes this program can save files to");
    for volume in crate::source_volumes() {
        out.push(Line::blank());
        out.push(title(format!("  {}", volume.name)));
        out.push(dim(format!("    {}", volume.path)));
        out.push(field("removable", if volume.removable { "yes" } else { "no" }));
        match volume.free {
            Some(free) => out.push(field("free space", human_size(free))),
            None => out.push(field("free space", "the filesystem would not say")),
        }
        match volume.names() {
            Ok(names) if names.is_empty() => {
                out.push(field(&format!("\\{}", store::DIR), "empty, or not there yet"))
            }
            Ok(names) => {
                out.push(field(&format!("\\{}", store::DIR), format!("{} files", names.len())));
                for name in names {
                    out.push(dim(format!("      {name}")));
                }
            }
            Err(e) => out.push(field_as(Style::Bad, &format!("\\{}", store::DIR), e)),
        }
    }
    out
}

// -------------------------------------------------------- the variable store

/// A refusal to walk the variable store for ever.
///
/// `GetNextVariableName` is firmware-driven iteration, and firmware that
/// repeats a key or never says `NOT_FOUND` is a known enough bug class to
/// be worth a bound: the watchdog is disarmed for the whole session (see
/// [`main`](crate::main)), so a loop here is a machine that has to be held
/// down rather than a screen that says something unhelpful. Real machines
/// hold a few dozen to a few hundred; a report that stops after a thousand
/// and says so has lost nothing anybody was going to read. The same bound
/// guards the walk in [`crate::nvram`].
const MAX_VARIABLES: usize = nvram::MAX_VARIABLES;

/// The name, vendor and size of every variable in the store.
///
/// Last, because it is the least readable section and the most complete
/// one: it is a stock-take rather than a diagnosis. It has been worth
/// having exactly when the rest of the report looks fine — a variable store
/// with two hundred stale entries in it, or a `Boot0003` under a vendor
/// GUID nobody expected, is invisible everywhere else in this tool.
///
/// Bounded by [`MAX_VARIABLES`], because this is the one loop here whose end
/// the firmware decides. Two passes, the same way [`crate::nvram`] reads
/// entries: the names are all collected before any is sized, because
/// calling `GetVariable` in the middle of a live `GetNextVariableName`
/// walk is not something every firmware tolerates.
fn variable_store() -> Vec<Line> {
    let mut out = section("Every variable in the store (names and sizes only)");
    let mut total = 0usize;
    let mut rows = Vec::new();

    let mut keys = Vec::new();
    for var in runtime::variable_keys() {
        if keys.len() >= MAX_VARIABLES {
            rows.push(bad(format!("  stopped after {MAX_VARIABLES} variables; there are more")));
            break;
        }
        match var {
            Ok(var) => keys.push(var),
            Err(e) => {
                rows.push(bad(format!("  the walk stopped early ({:?})", e.status())));
                break;
            }
        };
    }
    let count = keys.len();

    for var in &keys {
        let name = &var.name;
        let size = match nvram::size_of(name, &var.vendor) {
            Ok(Some(n)) => {
                total += n;
                format!("{n} bytes")
            }
            Ok(None) => String::from("vanished while being read"),
            Err(e) => e,
        };
        // `name.to_string()` and not `name`: `CStr16`'s Display writes one
        // character at a time, so a width spec applied to it pads every
        // character rather than the string, and the column comes out
        // forty spaces wide per letter.
        rows.push(dim(format!(
            "  {:<40} {:>14}  {}",
            name.to_string(),
            size,
            vendor_name(&var.vendor)
        )));
    }

    out.push(dim(format!("  {count} variables, {} in total.", human_size(total as u64))));
    out.push(Line::blank());
    out.push(dim(format!("  {:<40} {:>14}  {}", "name", "size", "vendor")));
    out.extend(rows);
    out
}

/// The two vendor GUIDs the spec names, and the rest as themselves.
fn vendor_name(vendor: &VariableVendor) -> String {
    if *vendor == VariableVendor::GLOBAL_VARIABLE {
        String::from("global")
    } else if *vendor == VariableVendor::IMAGE_SECURITY_DATABASE {
        String::from("image security database")
    } else {
        vendor.0.to_string()
    }
}
